fikse feil

diff --git a/.github/workflows/deploy-nais-app.yml b/.github/workflows/deploy-nais-app.yml
--- a/.github/workflows/deploy-nais-app.yml
+++ b/.github/workflows/deploy-nais-app.yml
@@ -24,15 +24,11 @@ jobs:
         id: check-yaml
         run: echo "file-exists=$(test -f nais/app-${{ inputs.nav-environment }}.yaml && echo 'config_exists' || echo 'config_not_exists')" >> $GITHUB_OUTPUT
       - uses: nais/deploy/actions/deploy@v2
-        if: ${{ steps.check-json.outputs.file-exists == 'config_exists' }}
+        if: ${{ steps.check-yaml.outputs.file-exists == 'config_exists' }}
         env:
           CLUSTER: ${{ inputs.nav-cluster }}
           RESOURCE: nais/app-${{ inputs.nav-environment }}.yaml
           VAR: image=${{ inputs.image }}
       - name: No config files detected - unable to deploy
-        if: ${{ steps.check-json.outputs.file-exists != 'config_exists' }}
-        run: echo "::warning title=Unable to deploy::Could not find nais/app-${{ inputs.nav-environment }}.yaml" |
-             echo "${{ inputs.image }}" |
-             echo "${{ inputs.nav-cluster }}" |
-             echo "${{ inputs.nav-environment }}" |
-             echo "nais/app-${{ inputs.nav-environment }}.yaml"
+        if: ${{ steps.check-yaml.outputs.file-exists != 'config_exists' }}
+        run: echo "::warning title=Unable to deploy::Could not find nais/app-${{ inputs.nav-environment }}.yaml";exit 1
